name: test-depend

# STATUS: Testing FOLIO-2913

on:
  workflow_run:
    workflows: [ api-lint ]
    types: [ completed ]
    branches: [ folio-2913-depend-workflow ]

jobs:
  test-depend:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Verify depend
      run: echo "This would only run if api-lint was completed with success."

